# Generated by Django 5.1.5 on 2025-02-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onecode',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
