# Generated by Django 5.1.5 on 2025-02-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Build_Board', '0002_alter_advert_author_feedback_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert_feedback', to='Build_Board.advert'),
        ),
    ]
