# Generated by Django 4.2.18 on 2025-02-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Build_Board', '0004_remove_customer_max_otp_try_remove_customer_otp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimeCode',
        ),
    ]
