# Generated by Django 5.1.5 on 2025-02-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Build_Board', '0005_delete_onetimecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='customer',
        ),
    ]
